// // <copyright file="SettingsData.cs" company="PublicDomainWeekly.com">
// //     CC0 1.0 Universal (CC0 1.0) - Public Domain Dedication
// //     https://creativecommons.org/publicdomain/zero/1.0/legalcode
// // </copyright>
// // <auto-generated />

namespace PublicDomain
{
    // Directives
    using System.Collections.Generic;
    using System.Data;
    using System.Drawing;

    /// <summary>
    /// Urlister settings.
    /// </summary>
    public class SettingsData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="T:PublicDomain.SettingsData"/> class.
        /// </summary>
        public SettingsData()
        {
            // Parameterless constructor
        }

        /// <summary>
        /// The top most.
        /// </summary>
        public bool TopMost { get; set; } = false;

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="T:PublicDomainWeekly.SettingsData"/> is control.
        /// </summary>
        /// <value><c>true</c> if control; otherwise, <c>false</c>.</value>
        public bool Control { get; set; } = true;

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="T:PublicDomainWeekly.SettingsData"/> is alternate.
        /// </summary>
        /// <value><c>true</c> if alternate; otherwise, <c>false</c>.</value>
        public bool Alt { get; set; } = false;

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="T:PublicDomainWeekly.SettingsData"/> is shift.
        /// </summary>
        /// <value><c>true</c> if shift; otherwise, <c>false</c>.</value>
        public bool Shift { get; set; } = false;

        /// <summary>
        /// Gets or sets the hotkey.
        /// </summary>
        /// <value>The hotkey.</value>
        public string Hotkey { get; set; } = "H";

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="T:PublicDomain.SettingsData"/> open popup on cursor location.
        /// </summary>
        /// <value><c>true</c> if open popup on cursor location; otherwise, <c>false</c>.</value>
        public bool OpenPopupOnCursorLocation { get; set; } = true;

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="T:PublicDomain.SettingsData"/> close popup on selection.
        /// </summary>
        /// <value><c>true</c> if close popup on selection; otherwise, <c>false</c>.</value>
        public bool ClosePopupOnSelection { get; set; } = true;

        /// <summary>
        /// Gets or sets the saved items.
        /// </summary>
        /// <value>The saved items.</value>
        public string SavedItems { get; set; } = string.Empty;

        /// <summary>
        /// The auto paste delay.
        /// </summary>
        public int AutoPasteDelay = 1000;
    }
}